package tor

import "fmt"

// generateTorrc renders the torrc content for cfg per AI.md PART 31
// "Tor Configuration Optimizations" → getTorConfig(). The hidden service
// itself is created via the control port's ADD_ONION command, never via a
// torrc HiddenServiceDir stanza — this file only configures the Tor
// daemon's own behavior (bandwidth, logging, disabled relay/exit/dir
// functions, and the SOCKS port for optional outbound use).
//
// logFile is the absolute path to {log_dir}/tor.log (AI.md PART 31
// "Storage Locations") — Tor is told to log there directly via a
// `Log notice file` directive so tor.log is actually produced.
func generateTorrc(cfg Config, logFile string) string {
	socksConfig := "SocksPort 0"
	if cfg.UseNetwork {
		socksConfig = "SocksPort auto"
	}

	safeLogging := "1"
	if !cfg.SafeLogging {
		safeLogging = "0"
	}

	accountingConfig := ""
	if cfg.MaxMonthlyBandwidth != "" && cfg.MaxMonthlyBandwidth != "unlimited" {
		accountingConfig = fmt.Sprintf("\n# Monthly bandwidth limit\nAccountingStart month 1 00:00\nAccountingMax %s\n", cfg.MaxMonthlyBandwidth)
	}

	return fmt.Sprintf(`# ============================================================
# Tor Configuration - Generated by the %s server binary
# This file is PERSISTENT - it is not regenerated on normal startup.
# It is only rewritten when the operator changes server.yml tor settings.
# ============================================================

# Send Tor's own log output to the app-managed tor.log (AI.md PART 31
# "Storage Locations" — {log_dir}/tor.log)
Log notice file %s

# SOCKS port for outbound connections (0 = disabled, auto = runtime port)
# NEVER uses the system Tor default SOCKS/control ports - this is a
# dedicated per-app process, runtime-assigned ports only
%s

# Control port on a runtime-assigned localhost port (AI.md PART 31 —
# "Use ControlPort 127.0.0.1:auto on all OSes"). Never hardcode the
# system Tor default control port.
ControlPort 127.0.0.1:auto

# Authenticate the control connection with a cookie file — bine's control
# client uses SAFECOOKIE authentication by default (--CookieAuthentication 1).
CookieAuthentication 1

# Security hardening
SafeLogging %s

# Circuit limits (from server.tor.max_circuits / server.tor.circuit_timeout)
MaxClientCircuitsPending %d
CircuitBuildTimeout %d
MaxCircuitDirtiness 600

# Bandwidth limits per second (from config)
BandwidthRate %s
BandwidthBurst %s
%s
# Disable unused features - not a relay or exit
ExitRelay 0
ExitPolicy reject *:*
ORPort 0
DirPort 0

# Hidden service optimizations (actual HS created via ADD_ONION)
HiddenServiceSingleHopMode 0
HiddenServiceNumIntroductionPoints %d
HiddenServiceMaxStreams %d

# Faster startup
FetchDirInfoEarly 1
FetchDirInfoExtraEarly 1

# Reduce memory usage
DisableDebuggerAttachment 1
`, projectDisplayName, logFile, socksConfig, safeLogging, cfg.MaxCircuits, cfg.CircuitTimeout, cfg.BandwidthRate, cfg.BandwidthBurst, accountingConfig, cfg.NumIntroPoints, cfg.MaxStreamsPerCircuit)
}

// projectDisplayName is the fixed internal project name used in generated
// file headers. Frozen per PART 2/3 {internal_name} rules — never renamed.
const projectDisplayName = "airports"
